### ISSUE TITLE
Cryptic no hstore extension installed exception

### ISSUE THREAD

**Issue by Skinney** [layerware/hugsql#7]
I'm converting all my yesql code to hugsql, and I've run into this very strange bug. Need some helping in understanding why this happens.

I'm trying to run the following sql:

```
--:name create! :!
INSERT INTO shows (tvdb_id, name, description, banner, poster, network, next_update)
VALUES (:v:tvdb_id, :v:name, :v:description, :v:banner, :v:poster, :v:network, :v:next_update);
```

tvdb_id is an int, next_update is a joda-time instance. The other values are strings.

Postgres displays the following::

```
LOG:  execute <unnamed>: SHOW TRANSACTION ISOLATION LEVEL
LOG:  execute <unnamed>: BEGIN
LOG:  execute <unnamed>: INSERT INTO shows (tvdb_id, name, description, banner, poster, network, next_update)
	VALUES ($1, $2, $3, $4, $5, $6, $7)
DETAIL:  parameters: $1 = '278518', $2 = 'Last Week Tonight with John Oliver', $3 = 'Last Week Tonight with John Oliver is an American late-night talk and news satire television program.
	L.W.T draws its comedy and satire from recent news stories, political figures, media organizations, pop culture and often aspects of the show itself.', $4 = 'graphical/278518-g3.jpg', $5 = 'posters/278518-2.jpg', $6 = 'HBO', $7 = '2015-11-09 01:00:00+01'
LOG:  execute <unnamed>: SELECT pg_type.oid   FROM pg_catalog.pg_type   LEFT   JOIN (select ns.oid as nspoid, ns.nspname, r.r           from pg_namespace as ns           join ( select s.r, (current_schemas(false))[s.r] as nspname                    from generate_series(1, array_upper(current_schemas(false), 1)) as s(r) ) as r          using ( nspname )        ) as sp     ON sp.nspoid = typnamespace  WHERE typname = $1  ORDER BY sp.r, pg_type.oid DESC LIMIT 1
DETAIL:  parameters: $1 = 'hstore'
LOG:  execute S_3: ROLLBACK
```

And this is my stacktrace:

```
ERROR] org.postgresql.util.PSQLException: No hstore extension installed.
org.postgresql.util.PSQLException: No hstore extension installed.
	at org.postgresql.jdbc2.AbstractJdbc2Statement.setMap(AbstractJdbc2Statement.java:1746)
	at org.postgresql.jdbc2.AbstractJdbc2Statement.setObject(AbstractJdbc2Statement.java:2138)
	at org.postgresql.jdbc3g.AbstractJdbc3gStatement.setObject(AbstractJdbc3gStatement.java:38)
	at org.postgresql.jdbc4.AbstractJdbc4Statement.setObject(AbstractJdbc4Statement.java:48)
	at com.zaxxer.hikari.proxy.HikariPreparedStatementProxy.setObject(HikariPreparedStatementProxy.java)
	at clojure.java.jdbc$eval1178$fn__1179.invokePrim(jdbc.clj:341)
	at clojure.java.jdbc$eval1178$fn__1179.invoke(jdbc.clj)
	at clojure.java.jdbc$eval1157$fn__1158$G__1148__1167.invoke(jdbc.clj:328)
	at clojure.java.jdbc$set_parameters$fn__1254.invoke(jdbc.clj:478)
	at clojure.core$map_indexed$mapi__6824$fn__6825.invoke(core.clj:7015)
	at clojure.lang.LazySeq.sval(LazySeq.java:40)
	at clojure.lang.LazySeq.seq(LazySeq.java:49)
	at clojure.lang.RT.seq(RT.java:507)
	at clojure.core$seq__4128.invoke(core.clj:137)
	at clojure.core$dorun.invoke(core.clj:3009)
	at clojure.java.jdbc$set_parameters.invoke(jdbc.clj:477)
	at clojure.java.jdbc$db_query_with_resultset$run_query_with_params__1341.invoke(jdbc.clj:823)
	at clojure.java.jdbc$db_query_with_resultset.invoke(jdbc.clj:831)
	at clojure.java.jdbc$query.doInvoke(jdbc.clj:866)
	at clojure.lang.RestFn.invoke(RestFn.java:425)
	at hugsql.adapter.clojure_java_jdbc.HugsqlAdapterClojureJavaJdbc.query(clojure_java_jdbc.clj:15)
	at episode_next.db.show$id_for_tvdb_id.invoke(show.clj:5)
	at episode_next.db.show$id_for_tvdb_id.invoke(show.clj:5)
	at episode_next.routes.show$upsert_show_BANG_$fn__59504.invoke(show.clj:20)
	at clojure.java.jdbc$db_transaction_STAR_.doInvoke(jdbc.clj:595)
	at clojure.lang.RestFn.invoke(RestFn.java:521)
	at clojure.java.jdbc$db_transaction_STAR_.doInvoke(jdbc.clj:611)
	at clojure.lang.RestFn.invoke(RestFn.java:425)
	at episode_next.routes.show$upsert_show_BANG_.invoke(show.clj:18)
	at episode_next.routes.show$connect_show__GT_device_BANG_$fn__59513.invoke(show.clj:39)[INFO] /show/follow 500 194ms {:device-id #uuid "4443b630-8534-11e5-898f-0e2267e517ab", :tvdb-id 278518}

	at episode_next.routes.show$connect_show__GT_device_BANG_.invoke(show.clj:38)
	at episode_next.routes.show$eval59517$fn__59518.invoke(show.clj:53)
	at clojure.lang.MultiFn.invoke(MultiFn.java:229)
	at episode_next.http$router.invoke(http.clj:32)
	at episode_next.http$wrap_components$fn__60290.invoke(http.clj:27)
	at episode_next.http$wrap_error_page$fn__60287.invoke(http.clj:20)
	at episode_next.transit$wrap_transit_response$fn__60226.invoke(transit.clj:44)
	at episode_next.transit$wrap_transit_body$fn__60223.invoke(transit.clj:38)
	at episode_next.log$wrap_with_logger$fn__59304.invoke(log.clj:29)
	at aleph.http.server$wrap_stream__GT_input_stream$fn__21998.invoke(server.clj:403)
	at aleph.http.server$handle_request$fn__21916$f__17232__auto____21917.invoke(server.clj:153)
	at clojure.lang.AFn.run(AFn.java:22)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

Any idea why this is happening?

**Comment by csummers** [comment]
That is strange.  Can you show the output of the -sqlvec version of the function with the data you are passing in?

**Comment by Skinney** [comment]
Tested with both clojure.jdbc and clojure.java.jdbc adapter.

```
["INSERT INTO shows (tvdb_id, name, description, banner, poster, network, next_update)\nVALUES (?, ?, ?, ?, ?, ?, ?);" 278518 "Last Week Tonight with John Oliver" "Last Week Tonight with John Oliver is an American late-night talk and news satire television program.  \nL.W.T draws its comedy and satire from recent news stories, political figures, media organizations, pop culture and often aspects of the show itself." "graphical/278518-g3.jpg" "posters/278518-2.jpg" "HBO" #object[org.joda.time.DateTime 0xef92810 "2015-11-09T00:00:00.000Z"]]
```

**Comment by Skinney** [comment]
Here is the sql table, if it helps:

```
--:name m-setup-shows! :!
CREATE TABLE shows (
       id SERIAL PRIMARY KEY,
       tvdb_id int UNIQUE NOT NULL,
       name text NOT NULL,
       description text,
       banner text,
       poster text,
       network text,
       next_update timestamp with time zone
);
```

**Comment by Skinney** [comment]
So sorry about this. I read the stacktrace wrong. The problem was another query where I passed a map instead of a value. HugSQL could probably use better error-handling, but I see you already have that on your todo-list :)
